### ISSUE TITLE
whitespace in urls breaking link to css

### ISSUE THREAD

**Issue by radiovisual** [unstoppablecarl/metalsmith-relative-path-example#1]
There is unnecessary whitespace added to your generated urls, which breaks your relative urls on some pages. 

For example, the 'home' page renders perfectly, but the subpages (email, services, etc) have broken links to the css files.

For example:
`build/%20assets/css/bootstrap.min.css`

Otherwise, its a useful example. Thanks!

**Comment by unstoppablecarl** [comment]
fixed
